apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: arguswatchers.arguscontroller.clustergarage.io
spec:
  group: arguscontroller.clustergarage.io
  version: v1alpha1
  scope: Namespaced
  names:
    kind: ArgusWatcher
    singular: arguswatcher
    plural: arguswatchers
    shortNames:
    - aw
    categories:
    - all
  subresources:
    status: {}
  additionalPrinterColumns:
  - name: Observable
    type: integer
    description: Number of pods that can be watched
    JSONPath: .status.observablePods
  - name: Watched
    type: integer
    description: Number of pods currently being watched
    JSONPath: .status.watchedPods
