title: fim-k8s
description: File Integrity Monitoring for Kubernetes
baseurl: /fim-k8s
#url: "https://clustergarage.io/fim-k8s"
permalink: /:title/
brand:
  #image: logo.svg # upload logo to /assets/img/ folder
  text: fim-k8s
collections:
  docs:
    output: true
authors:
  adam:
    name: Adam Kentosh
    github: akentosh
  brett:
    name: Brett Fowle
    github: bfowle
  mike:
    name: Mike Sandman
    github: n8behavior
  team:
    name: ClusterGarage
    github: clustergarage
footer:
  copyright: Lorem ipsum dolor <a href="">sit amet</a> consectetur adipiscing elit
#google_analytics:
markdown: kramdown
highlighter: rouge
sass:
  style: compressed
remote_theme: clustergarage/docs-theme
plugins:
- jekyll-avatar
- jekyll-code-tabs
- jekyll-feed
- jekyll-remote-theme
- jekyll-seo-tag
exclude:
- README.md
- Gemfile
- Gemfile.lock
- node_modules
