---
apiVersion: arguscontroller.clustergarage.io/v1alpha1
kind: ArgusWatcher
metadata:
  name: djangoex-argus-watcher
spec:
  selector:
    matchLabels:
      app: django-ex
  subjects:
  - paths:
    - /opt/app-root
    events:
    - create
    - modify
