---
apiVersion: arguscontroller.clustergarage.io/v1alpha1
kind: ArgusWatcher
metadata:
  name: guestbook-ftnd-argus-watcher
spec:
  selector:
    matchLabels:
      app: guestbook
      tier: frontend
  subjects:
  - paths:
    - /var/www/html
    events:
    - modify
---
apiVersion: arguscontroller.clustergarage.io/v1alpha1
kind: ArgusWatcher
metadata:
  name: guestbook-bknd-argus-watcher
spec:
  selector:
    matchLabels:
      app: redis
      tier: backend
  subjects:
  - paths:
    - /data
    events:
    - create
    - modify
