---
apiVersion: arguscontroller.clustergarage.io/v1alpha1
kind: ArgusWatcher
metadata:
  name: nginx-argus-watcher
spec:
  selector:
    matchLabels:
      run: nginx
  subjects:
  - paths:
    - /var/log/nginx
    events:
    - modify
