apiVersion: v1
kind: ServiceAccount
metadata:
  name: fim-admin
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: fim-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: fim-admin
  namespace: kube-system
---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: fimwatchers.fimcontroller.clustergarage.io
spec:
  group: fimcontroller.clustergarage.io
  version: v1alpha1
  names:
    kind: FimWatcher
    singular: fimwatcher
    plural: fimwatchers
    shortNames:
    - fw
  scope: Namespaced
