apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fimd.clustergarage.io
  namespace: kube-system
  labels:
    daemon: fimd
spec:
  selector:
    matchLabels:
      daemon: fimd
  template:
    metadata:
      labels:
        daemon: fimd
    spec:
      containers:
      - name: fimd
        image: clustergarage/fimd:latest
        ports:
        - containerPort: 50051
        volumeMounts:
        - name: dockerpid
          mountPath: /var/run/docker.pid
        - name: dockersock
          mountPath: /var/run/docker.sock
        - name: sysfscgroup
          mountPath: /sys/fs/cgroup
        securityContext:
          privileged: true
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
      hostPID: true
      #tolerations:
      #- key: node-role.kubernetes.io/master
      #  effect: NoSchedule
      volumes:
      - name: dockerpid
        hostPath:
          path: /var/run/docker.pid
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
      - name: sysfscgroup
        hostPath:
          path: /sys/fs/cgroup
      serviceAccountName: fim-admin
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: fimd-svc
  namespace: kube-system
spec:
  type: NodePort
  selector:
    daemon: fimd
  ports:
  - name: grpc
    protocol: TCP
    port: 50051
    targetPort: 50051
