namespace: argus
serviceAccount: argus-admin
clusterRoleBinding: argus-admin
configMap:
  name: argus-config
controller:
  name: arguscontroller
  image: clustergarage/argus-controller:v0.5.0
  replicas: 1
  probePort: 5000
  prometheus:
    name: argus-prometheus
    portName: prometheus
    port: 2112
daemon:
  name: argusd
  image: clustergarage/argusd:v0.5.0
  probePort: 50051
  container:
    port: 50051
    portName: grpc
  svc:
    name: argusd-svc
    portName: grpc
