apiVersion: v1
entries:
  argus:
  - apiVersion: v1
    appVersion: "v0.5.0"
    created: 2018-09-26T22:42:09.595567532-04:00
    description: Helm chart for Argus - File Integrity Monitoring.
    digest: 234ed000e10d3488bb2bbb08088d32b2cb005d58b2f66d32308db6076f6afda0
    name: argus
    urls:
    - https://github.com/clustergarage/argus/releases/download/v0.5.0/argus-0.5.0.tgz
    version: 0.5.0
generated: 2018-09-26T22:42:09.595284361-04:00
