---
apiVersion: arguscontroller.clustergarage.io/v1alpha1
kind: ArgusWatcher
metadata:
  name: sidecar-argus-watcher
  namespace: jenkins
spec:
  selector:
    matchLabels:
      app: jenkins
  subjects:
  - paths:
    - /var/lib/jenkins/password
    - /var/lib/jenkins/secret.key
    - /var/lib/jenkins/secrets
    - /etc/nginx
    events:
    - modify
  - paths:
    - /var/lib/jenkins
    ignore:
    - .groovy
    - .java
    - .pki
    - plugins
    - war
    events:
    - open
    recursive: true
    tags:
      foo: bar
