---
apiVersion: arguscontroller.clustergarage.io/v1alpha1
kind: ArgusWatcher
metadata:
  name: sidecar-argus-watcher
  namespace: jenkins
spec:
  selector:
    matchLabels:
      app: jenkins
  subjects:
  - paths:
    - /var/lib/jenkins/logs
    - /var/log/nginx
    events:
    - modify
