apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: fimwatchers.fimcontroller.clustergarage.io
spec:
  group: fimcontroller.clustergarage.io
  version: v1alpha1
  names:
    kind: FimWatcher
    singular: fimwatcher
    plural: fimwatchers
    shortNames:
    - fw
  scope: Namespaced
