apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{.Values.daemon.name}}
  namespace: {{.Values.namespace}}
  labels:
    daemon: {{.Values.daemon.name}}
spec:
  selector:
    matchLabels:
      daemon: {{.Values.daemon.name}}
  template:
    metadata:
      labels:
        daemon: {{.Values.daemon.name}}
    spec:
      containers:
      - name: {{.Values.daemon.name}}
        image: {{.Values.daemon.image | quote}}
        ports:
        - name: {{.Values.daemon.container.portName}}
          containerPort: {{.Values.daemon.container.port}}
        livenessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr", ":{{.Values.daemon.probePort}}"]
          initialDelaySeconds: 10
        readinessProbe:
          exec:
            command: ["/bin/grpc_health_probe", "-addr", ":{{.Values.daemon.probePort}}"]
          initialDelaySeconds: 5
        volumeMounts:
        - name: dockerpid
          mountPath: /var/run/docker.pid
        - name: dockersock
          mountPath: /var/run/docker.sock
        - name: sysfscgroup
          mountPath: /sys/fs/cgroup
        securityContext:
          privileged: true
      hostPID: true
      serviceAccountName: {{.Values.serviceAccount}}
      volumes:
      - name: dockerpid
        hostPath:
          path: /var/run/docker.pid
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
      - name: sysfscgroup
        hostPath:
          path: /sys/fs/cgroup
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.daemon.svc.name}}
  namespace: {{.Values.namespace}}
  labels:
    daemon: {{.Values.daemon.name}}
spec:
  selector:
    daemon: {{.Values.daemon.name}}
  clusterIP: None
  ports:
  - name: {{.Values.daemon.svc.portName}}
    port: {{.Values.daemon.container.port}}
    targetPort: {{.Values.daemon.container.portName}}
